In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
from scipy.ndimage import gaussian_filter

In [2]:
path_to_file = './philly_ped_vehicle.csv' 
df = pd.read_csv(path_to_file)

In [57]:
from utils import filter as ft
from utils import preprocess as ppr

input_variables =['weekday', 'datetimeoccur', 'point_x','point_y', 'districtoccur','psa',
                 'inside_or_outside','gender','age','race', 'success']

df_no_nans = ft.all_filters_for_input(df)   # performs all filtering of row data (many rows deleted). not yet
                                            # removed columns or added feature columns
df_no_nans_add_success = ppr.add_success_column(df_no_nans)
df_no_nans_add_success = df_no_nans_add_success[input_variables].copy() # 
df_input = ppr.add_local_hit_rate(df_no_nans_add_success)


/Users/tommytang/Documents/Data_Science_Projects/philly-frisks/utils/preprocess.py:68: RuntimeWarning: invalid value encountered in true_divide
  return np.divide(blurred_success, blurred_indicator)


In [58]:
df_input

weekday        datetimeoccur    point_x    point_y  districtoccur  \
36          FRIDAY  2014-10-24 20:00:00 -75.230402  39.939366           12.0   
63          FRIDAY  2014-10-24 08:53:00 -75.080879  40.078241            7.0   
83          FRIDAY  2014-09-19 11:57:00 -75.171483  39.980504           22.0   
85        SATURDAY  2014-11-15 22:48:00 -75.175287  39.990547           22.0   
116         FRIDAY  2014-03-07 16:35:00 -75.172644  39.982351           22.0   
154         FRIDAY  2014-10-24 22:20:00 -75.134377  39.974972           26.0   
179         FRIDAY  2014-10-24 12:00:00 -75.238296  39.956160           18.0   
206         FRIDAY  2014-10-24 21:00:00 -75.051821  40.061231            7.0   
207         FRIDAY  2014-10-24 21:00:00 -75.051821  40.061231            7.0   
208         FRIDAY  2014-10-24 20:55:00 -75.051670  40.063089            7.0   
214         FRIDAY  2014-10-24 19:25:00 -75.108483  39.995693           24.0   
247         FRIDAY  2014-10-24 17:04:00 -75.218899  39.938359           12.0   
251         FRIDAY  2014-10-24 17:10:00 -75.232690  39.943627           12.0   
258         FRIDAY  2014-10-24 01:47:00 -75.179613  40.035919           14.0   
259         FRIDAY  2014-10-24 01:47:00 -75.179613  40.035919           14.0   
285         FRIDAY  2014-10-24 08:51:00 -75.045956  40.024608           15.0   
294         FRIDAY  2014-10-24 18:43:00 -75.170179  39.967260            9.0   
295         FRIDAY  2014-10-24 18:43:00 -75.170179  39.967260            9.0   
296         FRIDAY  2014-10-24 18:50:00 -75.168571  39.967236            9.0   
323         SUNDAY  2014-10-19 21:25:00 -75.108732  39.998969           24.0   
335       SATURDAY  2014-10-25 16:20:00 -75.180230  40.044972           14.0   
359       SATURDAY  2014-11-22 22:00:00 -75.075061  40.041993            2.0   
396         FRIDAY  2014-10-24 14:44:00 -75.194444  39.955051           18.0   
397         FRIDAY  2014-10-24 14:43:00 -75.194234  39.955523           18.0   
405         FRIDAY  2014-10-24 19:00:00 -75.213697  39.955454           18.0   
406         FRIDAY  2014-10-24 18:55:00 -75.227726  39.956066           18.0   
410         FRIDAY  2014-10-24 03:17:00 -75.258570  39.985521           19.0   
411         FRIDAY  2014-10-24 03:17:00 -75.258570  39.985521           19.0   
422         FRIDAY  2014-10-24 19:00:00 -75.159704  39.978487           22.0   
423         FRIDAY  2014-10-24 18:53:00 -75.177925  39.978326           22.0   
...            ...                  ...        ...        ...            ...   
2028884  WEDNESDAY  2018-07-25 10:45:00 -75.104772  39.984458           24.0   
2029028     SUNDAY  2018-08-26 14:25:00 -75.239962  39.961887           19.0   
2029078     FRIDAY  2018-07-27 02:03:00 -75.153697  39.967414            6.0   
2029083     FRIDAY  2018-07-27 02:03:00 -75.153697  39.967414            6.0   
2029093   SATURDAY  2018-07-28 00:51:00 -75.169810  39.924387            1.0   
2029146     FRIDAY  2018-08-17 20:30:00 -75.165664  39.997040           39.0   
2029219     FRIDAY  2018-07-27 18:40:00 -75.140952  40.026884           35.0   
2029221     FRIDAY  2018-07-27 18:40:00 -75.172206  40.017438           39.0   
2029231   SATURDAY  2018-08-18 11:50:00 -75.159800  39.923086            3.0   
2029239   SATURDAY  2018-08-18 17:52:00 -75.076862  40.023218           15.0   
2029240   SATURDAY  2018-08-18 17:52:00 -75.076862  40.023218           15.0   
2029301     FRIDAY  2018-08-17 20:12:00 -75.108507  40.035437            2.0   
2029342     FRIDAY  2018-08-17 00:24:00 -75.159162  40.027744           35.0   
2029437   THURSDAY  2018-08-16 22:00:00 -75.233280  39.959252           18.0   
2029500     FRIDAY  2018-08-17 22:24:00 -75.118795  40.027325           35.0   
2029541   SATURDAY  2018-08-18 17:00:00 -75.120266  40.011956           25.0   
2029634     FRIDAY  2018-07-27 10:50:00 -75.241950  39.947730           18.0   
2029674     FRIDAY  2018-08-17 18:15:00 -75.219324  39.957724           18.0   
2029686   S

In [6]:
a= df_input['local_hit_rate'].copy()

In [7]:
print('start here')

0.0

In [4]:
df.columns

Index(['the_geom', 'lng', 'objectid', 'id', 'datetimeoccur', 'weekday',
       'location', 'districtoccur', 'psa', 'stopcode', 'stoptype',
       'inside_or_outside', 'gender', 'the_geom_webmercator', 'age',
       'individual_frisked', 'individual_searched', 'individual_arrested',
       'individual_contraband', 'vehicle_frisked', 'vehicle_searched',
       'vehicle_contraband', 'point_x', 'point_y', 'lat', 'race'],
      dtype='object')

In [8]:
lhr_input = ppr.get_local_hit_rate_input(df_no_nans_add_success)
lhr_map = ppr.get_local_hit_rate_map(lhr_input)
points = ppr.local_hit_rate_input_to_map_coordinates(lhr_input)
lhr_column = ppr.local_hit_rates_from_map(lhr_map, points)

/Users/tommytang/Documents/Data_Science_Projects/philly-frisks/utils/preprocess.py:19: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return df.loc[:, colnames].values
/Users/tommytang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:1367: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)
/Users/tommytang/Documents/Data_Science_Projects/philly-frisks/utils/preprocess.py:68: RuntimeWarning: invalid value encountered in true_divide
  return np.divide(blurred_success, blurred_indicator)


In [16]:
type(lhr_column)

numpy.ndarray

In [11]:
test = lhr_map.copy()
test = np.nan_to_num(lhr_map)

In [17]:
sig = 12

In [22]:
success_map = ppr.local_hit_rate_input_to_success_map(lhr_input)
indicator_map = ppr.local_hit_rate_input_to_indicator_map(lhr_input)
blurred_success = gaussian_filter(success_map, sigma=sig)
blurred_indicator = gaussian_filter(indicator_map, sigma=sig)

In [26]:
s = np.nan_to_num(success_map)
np.sum(s)

0.0

In [28]:
points = lhr_input[:,[0,1]].copy()

In [33]:
point_x_column_index = 0
point_y_column_index = 1
map_limits = ppr.get_map_limits(lhr_input)
points[:,point_x_column_index] -= map_limits['min_x']
points[:,point_y_column_index] -= map_limits['min_y']

In [36]:
points 

array([[ 44,  63],
       [193, 202],
       [103, 105],
       ...,
       [110, 155],
       [ 57,  62],
       [120, 140]])

In [37]:
p = ppr.local_hit_rate_input_to_map_coordinates(lhr_input)

In [39]:
row_indices = points[:,1]

In [41]:
r_indices=row_indices.copy()

In [44]:
dilution = 1000
local_hit_rate_input = lhr_input.copy()
point_x = local_hit_rate_input[:, point_x_column_index].copy() * dilution
point_y = local_hit_rate_input[:, point_y_column_index].copy() * dilution
col_indices = np.round(point_x) - map_limits['min_x']
row_indices = np.round(point_y) - map_limits['min_y']
col_indices = col_indices.astype(int)
row_indices = row_indices.astype(int)

In [45]:
row_indices

array([ 63, 202, 105, ..., 155,  62, 140])

In [46]:
r_indices

array([ 63, 202, 105, ..., 155,  62, 140])

In [48]:
np.array_equal(row_indices, r_indices)

True

In [50]:
smap = ppr.initialize_map(ppr.get_map_limits(lhr_input))

In [51]:
smap[points[:,1],points[:,0]] = lhr_input[:,2]

In [53]:
np.sum(np.nan_to_num(smap))

0.0

In [54]:
point_x_column_index = 0
point_y_column_index = 1
success_values_column_index = 2
map_limits = ppr.get_map_limits(local_hit_rate_input)
success_map = ppr.initialize_map(map_limits)
point_x = local_hit_rate_input[:, point_x_column_index].copy() * dilution
point_y = local_hit_rate_input[:, point_y_column_index].copy() * dilution
col_indices = np.round(point_x) - map_limits['min_x']
row_indices = np.round(point_y) - map_limits['min_y']
col_indices = col_indices.astype(int)
row_indices = row_indices.astype(int)
success_values = local_hit_rate_input[:, success_values_column_index].copy()
assert(col_indices.shape == success_values.shape)
assert(row_indices.shape == success_values.shape)
success_map[row_indices, col_indices] = success_values

In [56]:
np.sum(np.nan_to_num(success_map))

0.0