In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

In [2]:
path_to_file = './philly_ped_vehicle.csv' 
df = pd.read_csv(path_to_file)

In [3]:
from utils import filter as ft
from utils import preprocess as ppr
df_no_nans = ft.all_filters_for_input(df)   # performs all filtering of row data (many rows deleted). not yet
                                            # removed columns or added feature columns
df_no_nans_add_success = ppr.add_success_column(df_no_nans)
local_hit_rate_input = ppr.get_local_hit_rate_input(df_no_nans_add_success)    
lhr_map = ppr.get_local_hit_rate_map(local_hit_rate_input)

input_variables =['weekday', 'datetimeoccur', 'lng','lat', 'districtoccur','psa',
                 'inside_or_outside','gender','age','race']

/Users/tommytang/Documents/Data_Science_Projects/philly-frisks/utils/preprocess.py:74: RuntimeWarning: invalid value encountered in true_divide
  return np.divide(blurred_success, blurred_indicator)


In [ ]:
# identify input variables
# subset out by column
# clean nulls if necessary
# transform as input to model

In [7]:
np.nan_to_num(lhr_map)

array([[0.53112715, 0.52659543, 0.51959445, ..., 0.        , 0.        ,
        0.        ],
       [0.52318369, 0.5188357 , 0.51211883, ..., 0.        , 0.        ,
        0.        ],
       [0.50777625, 0.50378393, 0.49761706, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.15201735, 0.12608684,
        0.10771424],
       [0.        , 0.        , 0.        , ..., 0.15206182, 0.12169522,
        0.09930008],
       [0.        , 0.        , 0.        , ..., 0.15270705, 0.11887288,
        0.09329934]])

array([[0.53112715, 0.52659543, 0.51959445, ...,        nan,        nan,
               nan],
       [0.52318369, 0.5188357 , 0.51211883, ...,        nan,        nan,
               nan],
       [0.50777625, 0.50378393, 0.49761706, ...,        nan,        nan,
               nan],
       ...,
       [       nan,        nan,        nan, ..., 0.15201735, 0.12608684,
        0.10771424],
       [       nan,        nan,        nan, ..., 0.15206182, 0.12169522,
        0.09930008],
       [       nan,        nan,        nan, ..., 0.15270705, 0.11887288,
        0.09329934]])

In [11]:
max(local_hit_rate_input[:,2])

1.0

In [7]:
file_name = 'philly-stops-clean.csv'
df_no_nans_add_success.to_csv(file_name, index=False)

In [6]:
pointx = local_hit_rate_input[:,0]

In [16]:
min(pointx)

-75.27301907

In [17]:
max(pointx)

-74.95883739

In [9]:
lhr_input = pd.DataFrame(local_hit_rate_input)

In [11]:
lhr_input.to_csv('lhr_input', index=False)

In [30]:
lhr = local_hit_rate_input.copy()

In [31]:
lhr

array([[-75.23040214,  39.93936553,   0.        ],
       [-75.08087913,  40.07824146,   0.        ],
       [-75.17148295,  39.98050433,   0.        ],
       ...,
       [-75.16364879,  40.03121862,   0.        ],
       [-75.21679953,  39.93796852,   0.        ],
       [-75.15395935,  40.01590183,   0.        ]])

In [36]:
a = lhr[:,1].copy()

In [38]:
a * 10

array([399.3936553, 400.7824146, 399.8050433, ..., 400.3121862,
       399.3796852, 400.1590183])

In [39]:
lhr[:,1]

array([39.93936553, 40.07824146, 39.98050433, ..., 40.03121862,
       39.93796852, 40.01590183])

In [46]:
a = np.array([[1,1],[2,2]])

In [47]:
np.sum(a)

6