In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

In [2]:
path_to_file = './philly_ped_vehicle.csv' 
df = pd.read_csv(path_to_file)

In [3]:
from utils import filter as ft
from utils import preprocess as ppr

input_variables =['weekday', 'datetimeoccur', 'point_x','point_y', 'districtoccur','psa',
                 'inside_or_outside','gender','age','race']

df_no_nans = ft.all_filters_for_input(df)   # performs all filtering of row data (many rows deleted). not yet
                                            # removed columns or added feature columns
df_no_nans_add_success = ppr.add_success_column(df_no_nans)
df_no_nans_add_success = df_no_nans_add_success[input_variables].copy()
df_input = ppr.add_local_hit_rate(df_no_nans_add_success)


/Users/tommytang/Documents/Data_Science_Projects/philly-frisks/utils/preprocess.py:19: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return df.loc[:, colnames].values
/Users/tommytang/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:1367: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)
/Users/tommytang/Documents/Data_Science_Projects/philly-frisks/utils/preprocess.py:68: RuntimeWarning: invalid value encountered in true_divide
  return np.divide(blurred_success, blurred_indicator)


[ 63 202 105]
[ 44 193 103]


In [5]:
df_input.columns

Index(['weekday', 'datetimeoccur', 'point_x', 'point_y', 'districtoccur',
       'psa', 'inside_or_outside', 'gender', 'age', 'race', 'local_hit_rate'],
      dtype='object')

In [6]:
a= df_input['local_hit_rate'].copy()

In [7]:
min

0.0

In [31]:
lhr

array([[-75.23040214,  39.93936553,   0.        ],
       [-75.08087913,  40.07824146,   0.        ],
       [-75.17148295,  39.98050433,   0.        ],
       ...,
       [-75.16364879,  40.03121862,   0.        ],
       [-75.21679953,  39.93796852,   0.        ],
       [-75.15395935,  40.01590183,   0.        ]])

In [36]:
a = lhr[:,1].copy()

In [38]:
a * 10

array([399.3936553, 400.7824146, 399.8050433, ..., 400.3121862,
       399.3796852, 400.1590183])

In [39]:
lhr[:,1]

array([39.93936553, 40.07824146, 39.98050433, ..., 40.03121862,
       39.93796852, 40.01590183])

In [4]:
a = np.array([[1,1],[2,2]])

In [3]:
import numpy as np

In [18]:
a.shape[0]

2

In [6]:
a = [0:1]

SyntaxError: invalid syntax (<ipython-input-6-3aaf0cd4bbe5>, line 1)